#!/usr/bin/env bash
#
# Localnet bootstrap (run AFTER start-validator.sh is up).
#
# Funds the payer + treasury wallets, creates a test $ASTROID mint, and
# writes the base .keys/localnet.env. Then run deploy-quarry.ts to fill
# in the QUARRY_* values. Idempotent enough to re-run after a validator
# --reset. No secrets here; keys + env live under the gitignored .keys/.
set -euo pipefail

KEYS="${KEYS_DIR:-.keys}"
RPC="${SOLANA_RPC_URL:-http://127.0.0.1:8899}"

solana config set --url "$RPC" --keypair "$KEYS/payer.json" >/dev/null

PAYER=$(solana-keygen pubkey "$KEYS/payer.json")
solana airdrop 500 "$PAYER" >/dev/null 2>&1 || true
for w in reward-wallet redeemer-wallet creator-wallet; do
  solana airdrop 100 "$(solana-keygen pubkey "$KEYS/$w.json")" >/dev/null 2>&1 || true
done

# Test $ASTROID mint — 6 decimals to match the intended mainnet token.
MINT=$(spl-token create-token --decimals 6 2>/dev/null | awk '/Address:/{print $2}')
spl-token create-account "$MINT" >/dev/null 2>&1
spl-token mint "$MINT" 1000000 >/dev/null 2>&1

cat > "$KEYS/localnet.env" <<EOF
# Localnet bootstrap values (gitignored). Generated by bootstrap.sh.
SOLANA_NETWORK=localnet
SOLANA_RPC_URL=$RPC
ASTROID_MINT_ADDRESS=$MINT
ASTROID_DECIMALS=6
PAYER_PUBKEY=$PAYER
REWARD_WALLET_PUBKEY=$(solana-keygen pubkey "$KEYS/reward-wallet.json")
REDEEMER_WALLET_PUBKEY=$(solana-keygen pubkey "$KEYS/redeemer-wallet.json")
CREATOR_WALLET_PUBKEY=$(solana-keygen pubkey "$KEYS/creator-wallet.json")
# Filled in by deploy-quarry.ts:
QUARRY_REWARDER_ADDRESS=
QUARRY_ADDRESS=
QUARRY_MINT_WRAPPER=
IOU_TOKEN_MINT=
EOF

echo "Bootstrapped. ASTROID test mint: $MINT (supply 1,000,000)"
echo "Next: npx tsx scripts/localnet/deploy-quarry.ts"
